import {beforeEach,describe,expect,it,vi} from 'vitest';
vi.mock('../src/server/workspace',()=>({ExchangeWorkspace:class{}}));
vi.mock('../src/server/payments',()=>({createFundingCheckout:vi.fn(),parseFundingWebhook:vi.fn()}));
import worker from '../src/server/index';
const owner='aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee',stage='11111111-2222-4333-8444-555555555555';
function setup(){const ws={registerBrandAgent:vi.fn().mockResolvedValue({brand:{id:'brand-test'},token:'once-only-token'}),listBrandAgents:vi.fn().mockResolvedValue({agents:[]}),revokeBrandAgent:vi.fn().mockResolvedValue({revoked:true}),brandAgentStatus:vi.fn().mockResolvedValue({brand:{id:'brand-test'},active:true}),brandAgentOpportunities:vi.fn().mockResolvedValue({opportunities:[]}),submitBrandAgentAction:vi.fn().mockResolvedValue({accepted:true,idempotent:false})};const env={ADMIN_TOKEN:'admin',OPERATOR_WORKSPACE_ID:owner,DEMO_WORKSPACE_ID:stage,PUBLISHER_API_KEYS:JSON.stringify({wavelength:'pub'}),EXCHANGE:{getByName:vi.fn().mockReturnValue(ws)}} as unknown as Env;const request=(path:string,method='GET',headers:Record<string,string>={},data?:object)=>worker.fetch(new Request('https://accord.example'+path,{method,headers,...(data?{body:JSON.stringify(data)}:{})}),env);return {ws,env,request};}
beforeEach(()=>vi.clearAllMocks());
describe('external brand HTTP ownership',()=>{
 it('allows only the operator to invite and list credentials, returning token only on creation',async()=>{const {ws,request}=setup();expect((await request('/v1/brand-agents','POST',{},{})).status).toBe(401);expect((await request('/v1/brand-agents','POST',{authorization:'Bearer pub','x-workspace-id':stage},{})).status).toBe(401);const created=await request('/v1/brand-agents','POST',{'x-admin-token':'admin','x-demo-workspace':stage},{});expect(created.status).toBe(201);expect(await created.json()).toMatchObject({workspace_id:stage,token:'once-only-token'});expect(ws.registerBrandAgent).toHaveBeenCalledTimes(1);expect(await (await request('/v1/brand-agents','GET',{'x-admin-token':'admin'})).json()).toEqual({agents:[]});});
 it('requires workspace and bearer before reaching agent storage',async()=>{const {env,request}=setup();expect((await request('/v1/brand-agent/opportunities')).status).toBe(401);expect((await request('/v1/brand-agent/status','GET',{'x-workspace-id':'99999999-9999-4999-8999-999999999999',authorization:'Bearer credential'})).status).toBe(401);expect(env.EXCHANGE.getByName).not.toHaveBeenCalled();});
 it('passes only scoped brand credentials to the external feed and action methods',async()=>{const {ws,request}=setup();const headers={authorization:'Bearer agent-credential','x-workspace-id':stage};expect((await request('/v1/brand-agent/opportunities','GET',headers)).status).toBe(200);expect(ws.brandAgentOpportunities).toHaveBeenCalledWith('agent-credential');const body={auction_id:'auction',round:1,round_token:'job',action:{action:'withdraw',explanation:'No offer'}};expect((await request('/v1/brand-agent/actions','POST',headers,body)).status).toBe(200);expect(ws.submitBrandAgentAction).toHaveBeenCalledWith('agent-credential',body);});
 it('maps revoked credentials and late offers to useful HTTP statuses',async()=>{const {ws,request}=setup();const headers={authorization:'Bearer revoked','x-workspace-id':stage};ws.brandAgentStatus.mockRejectedValue(new Error('Agent authentication required'));expect((await request('/v1/brand-agent/status','GET',headers)).status).toBe(401);ws.submitBrandAgentAction.mockRejectedValue(new Error('Round is closed or stale'));expect((await request('/v1/brand-agent/actions','POST',headers,{})).status).toBe(409);});
 it('does not let an external token read the operator ledger or invite more brands',async()=>{const {request}=setup();const headers={authorization:'Bearer external-secret','x-workspace-id':stage};expect((await request('/v1/ledger','GET',headers)).status).toBe(401);expect((await request('/v1/brand-agents','POST',headers,{})).status).toBe(401);});
 it('rejects cross-origin browser mutations even with an operator or agent credential',async()=>{const {request}=setup();expect((await request('/v1/brand-agent/actions','POST',{authorization:'Bearer token','x-workspace-id':stage,origin:'https://other.example'},{})).status).toBe(403);});
});
