import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import type {AgentAction,Auction,Campaign} from '../src/shared/types';
vi.mock('cloudflare:workers',()=>({DurableObject:class {constructor(public ctx:unknown,public env:unknown){}}}));
vi.mock('../src/server/agents',()=>({assessFits:vi.fn(),decideOffer:vi.fn()}));
import {assessFits,decideOffer} from '../src/server/agents';
import {harness,closeHarnesses} from './workspace-harness';
const input={name:'Pilot Coffee',scenario:'dating',item:'Two coffees',description:'Operator-provided pilot catalog.',base_price_cents:1600,source_url:'https://pilotcoffee.ca/',facts:['Coffee'],tags:['coffee'],code:'PILOT-DEMO',max_cpc_cents:200,max_discount_cents:700,strategy:'Offer useful discounts.'};
const action:AgentAction={action:'submit',bid_cents:100,discount_cents:500,explanation:'A customer offer.'};
beforeEach(()=>{vi.clearAllMocks();vi.useFakeTimers();vi.mocked(assessFits).mockImplementation(async a=>a.bidders.map(b=>({brand_id:b.brand.id,score:80,explanation:'Equal fit'})));vi.mocked(decideOffer).mockResolvedValue({action:'submit',bid_cents:50,discount_cents:0,explanation:'Managed offer'});});
afterEach(()=>{closeHarnesses();vi.useRealTimers();});
async function live(){const h=harness(),invite=await h.workspace.registerBrandAgent(input);await h.workspace.simulationFund(invite.brand.id,10000);await h.workspace.updateCampaign(invite.brand.id,{active:true});const a=await h.workspace.start({scenario:'dating',intent:'Coffee',preferences:['coffee'],mode:'live',payment_mode:'simulation',target_score:100});await h.internal.processAuction(a.id);await h.internal.processAuction(a.id);const o=(await h.workspace.brandAgentOpportunities(invite.token)).opportunities[0];return {h,invite,a,o,submit:{auction_id:a.id,round:o.round,round_token:o.round_token,action}};}
describe('external brand workspace protocol',()=>{
 it('registers an inactive unfunded dynamic catalog with hashed credentials only',async()=>{const h=harness(),invite=await h.workspace.registerBrandAgent(input);const boot=await h.workspace.bootstrap();expect(boot.brands.some(b=>b.id===invite.brand.id)).toBe(true);expect(boot.campaigns.find(c=>c.brand_id===invite.brand.id)).toMatchObject({active:false,balance_cents:0,agent_kind:'external'});expect(JSON.stringify(boot)).not.toContain(invite.token);expect(JSON.stringify(await h.workspace.listBrandAgents())).not.toContain('token_hash');expect(JSON.stringify(h.get('brand_agent',invite.brand.id))).not.toContain(invite.token);});
 it('gives only own private policy and previous completed public offers, never peer current submissions',async()=>{const {h,invite,o}=await live();expect(o.public_board).toEqual([]);expect(o.own_catalog.id).toBe(invite.brand.id);expect(o.own_campaign.max_discount_cents).toBe(700);expect(JSON.stringify(o)).not.toContain('token_hash');expect(Object.keys(o).sort()).toEqual(['auction_id','deadline','feedback','intent','own_campaign','own_catalog','own_fit','preferences','previous_offer','public_board','reference_price_cents','round','round_token'].sort());expect(decideOffer).toHaveBeenCalledTimes(3);expect(vi.mocked(decideOffer).mock.calls.every(([,b])=>b.brand.id!==invite.brand.id)).toBe(true);});
 it('accepts a scoped offer once and keeps it private until the sealed window closes',async()=>{const {h,invite,a,o,submit}=await live();expect(await h.workspace.submitBrandAgentAction(invite.token,submit)).toMatchObject({accepted:true,idempotent:false});expect(await h.workspace.submitBrandAgentAction(invite.token,submit)).toMatchObject({accepted:true,idempotent:true});expect((await h.workspace.readAuction(a.id)).rounds).toHaveLength(0);expect((await h.workspace.brandAgentOpportunities(invite.token)).opportunities).toHaveLength(0);vi.setSystemTime(Date.parse(o.deadline)+1);await h.internal.processAuction(a.id);const result=await h.workspace.readAuction(a.id);expect(result.rounds[0].leader_id).toBe(invite.brand.id);expect(result.trace?.filter(t=>t.kind==='agent.submission')).toHaveLength(1);});
 it('rejects replacement actions, stale tokens, invalid amounts, and late submissions',async()=>{const {h,invite,o,submit}=await live();await expect(h.workspace.submitBrandAgentAction(invite.token,{...submit,round_token:'wrong'})).rejects.toThrow('stale');await expect(h.workspace.submitBrandAgentAction(invite.token,{...submit,action:{...action,bid_cents:999}})).rejects.toThrow();expect(h.get('submission',`${submit.auction_id}:1:${invite.brand.id}`)).toBeUndefined();await h.workspace.submitBrandAgentAction(invite.token,submit);await expect(h.workspace.submitBrandAgentAction(invite.token,{...submit,action:{...action,discount_cents:550}})).rejects.toThrow('already has');vi.setSystemTime(Date.parse(o.deadline));await expect(h.workspace.submitBrandAgentAction(invite.token,submit)).rejects.toThrow('closed');});
 it('cannot submit as another brand or enter another scenario',async()=>{const {h,submit}=await live();const outsider=await h.workspace.registerBrandAgent({...input,scenario:'fashion'});await expect(h.workspace.submitBrandAgentAction(outsider.token,submit)).rejects.toThrow('not available');expect((await h.workspace.brandAgentOpportunities(outsider.token)).opportunities).toEqual([]);await expect(h.workspace.brandAgentStatus('bad-token')).rejects.toThrow('authentication');});
 it('revokes credentials and prevents campaign reactivation without changing committed historical offers',async()=>{const {h,invite,submit}=await live();await h.workspace.submitBrandAgentAction(invite.token,submit);await h.workspace.revokeBrandAgent(invite.brand.id);await expect(h.workspace.brandAgentStatus(invite.token)).rejects.toThrow('authentication');await expect(h.workspace.submitBrandAgentAction(invite.token,submit)).rejects.toThrow('authentication');await expect(h.workspace.updateCampaign(invite.brand.id,{active:true})).rejects.toThrow('Revoked');expect(h.get<Campaign>('campaign',invite.brand.id)?.active).toBe(false);});
 it('rejects action after acceptance and preserves the frozen winning offer',async()=>{const {h,invite,a,o,submit}=await live();await h.workspace.submitBrandAgentAction(invite.token,submit);vi.setSystemTime(Date.parse(o.deadline)+1);await h.internal.processAuction(a.id);await h.internal.processAuction(a.id);const next=(await h.workspace.brandAgentOpportunities(invite.token)).opportunities[0];await h.workspace.action(a.id,'accept');await expect(h.workspace.submitBrandAgentAction(invite.token,{...submit,round:next.round,round_token:next.round_token})).rejects.toThrow('closed');const result=await h.workspace.readAuction(a.id);expect(result.winner?.brand_id).toBe(invite.brand.id);expect(result.placement?.description).toBe(input.description);expect(result.rounds).toHaveLength(1);});
 it('retains a prior offer when an external agent misses a later deadline',async()=>{const {h,invite,a,o,submit}=await live();await h.workspace.submitBrandAgentAction(invite.token,submit);vi.setSystemTime(Date.parse(o.deadline)+1);await h.internal.processAuction(a.id);await h.internal.processAuction(a.id);const next=(await h.workspace.brandAgentOpportunities(invite.token)).opportunities[0];expect(next.public_board).toHaveLength(4);vi.setSystemTime(Date.parse(next.deadline)+1);await h.internal.processAuction(a.id);const result=await h.workspace.readAuction(a.id);expect(result.bidders.find(b=>b.brand.id===invite.brand.id)?.offer).toMatchObject({bid_cents:100,discount_cents:500});expect(result.rounds[1].actions[invite.brand.id]).toContain('timeout');});
 it('recovers persisted external submissions after a restart without redispatching models',async()=>{const {h,invite,a,o,submit}=await live();await h.workspace.submitBrandAgentAction(invite.token,submit);const restarted=harness(h.db);vi.setSystemTime(Date.parse(o.deadline)+1);await restarted.internal.processAuction(a.id);expect((await restarted.workspace.readAuction(a.id)).rounds[0].leader_id).toBe(invite.brand.id);expect(decideOffer).toHaveBeenCalledTimes(3);});
});
