import type { Brand, Campaign, Scenario } from './types';

const source_date = '2026-09-28';
export const brands: Brand[] = [
  { id:'blue-bottle', name:'Blue Bottle', initials:'BB', color:'#6faec8', scenario:'dating', item:'Ferry Building · two coffees', description:'A coffee stop at the Ferry Building in San Francisco.', base_price_cents:1600, price_kind:'demo_quote', source_url:'https://bluebottlecoffee.com/cafes/ferry-building', source_date, facts:['Listed address: 1 Ferry Building #7, San Francisco.','Two-coffee price is a simulated quote, not a merchant menu price.','Current operating availability is not verified; source currently lists closed hours.'], tags:['coffee','ferry building','waterfront','casual'], code:'BLUEBOTTLE-DEMO' },
  { id:'sightglass', name:'Sightglass', initials:'SG', color:'#c8ac86', scenario:'dating', item:'SoMa flagship · two coffees', description:'A roastery and open coffee bar at the 7th Street flagship.', base_price_cents:1600, price_kind:'demo_quote', source_url:'https://sightglasscoffee.com/pages/sightglass-san-francisco-soma', source_date, facts:['Flagship at 270 7th Street in SoMa.','Roastery and coffee preparation are visible from its open floor plan.','Two-coffee price is a simulated quote; no reservation or quietness claim.'], tags:['coffee','soma','roastery','craft','casual'], code:'SIGHTGLASS-DEMO' },
  { id:'ritual', name:'Ritual', initials:'R', color:'#ee6c60', scenario:'dating', item:'Mission café · two coffees', description:'Ritual’s Mission café on Valencia Street.', base_price_cents:1600, price_kind:'demo_quote', source_url:'https://ritualcoffee.com/locations/', source_date, facts:['Mission location at 1026 Valencia Street, San Francisco.','Two-coffee price is a simulated quote.','No live seating or reservation information.'], tags:['coffee','mission','valencia','neighborhood','casual'], code:'RITUAL-DEMO' },
  { id:'allbirds', name:'Allbirds', initials:'AB', color:'#c1c99a', scenario:'fashion', item:'Women’s Tree Runner Go · Natural White / Rustic Orange', description:'Breathable Tree Knit sneaker with a cushioned midsole.', base_price_cents:12000, price_kind:'snapshot', source_url:'https://www.allbirds.com/products/womens-tree-runner-go-natural-white-rustic-orange', source_date, facts:['Inspected USD price: $120 before tax and shipping.','Tree-fiber blend upper; machine washable with insoles removed and hand washed.','Page marks final sale; size availability and delivery are unverified.'], tags:['sneakers','walking','comfort','machine washable','easy cleaning','breathable'], code:'ALLBIRDS-DEMO' },
  { id:'rothys', name:'Rothy’s', initials:'R', color:'#c58cd1', scenario:'fashion', item:'The Ivy Sneaker · ReVelvet Black', description:'A low-profile sneaker with a knitted upper and foam insoles.', base_price_cents:14500, price_kind:'snapshot', source_url:'https://rothys.com/products/womens-ivy-sneaker-revelvet-black', source_date, facts:['Inspected USD price: $145 before tax and shipping.','ReVelvet upper made from recycled plastic bottles.','Shoes and insoles machine washable in cold water; air dry. Size availability is unverified.'], tags:['sneakers','walking','comfort','machine washable','easy cleaning','recycled'], code:'ROTHYS-DEMO' },
  { id:'everlane', name:'Everlane', initials:'E', color:'#e0b58d', scenario:'fashion', item:'The Day Sneaker · White', description:'A leather lace-up sneaker with a tapered toe and rubber outsole.', base_price_cents:4400, price_kind:'snapshot', source_url:'https://www.everlane.com/products/womens-day-sneaker-white', source_date, facts:['Inspected USD sale price: $44, reduced from $148; final sale.','Leather upper; professional leather cleaning or spot cleaning only.','No returns or exchanges on final sale. Size availability is unverified.'], tags:['sneakers','leather','minimal','white','style'], code:'EVERLANE-DEMO' },
  { id:'exploratorium', name:'Exploratorium', initials:'EX', color:'#f5b65a', scenario:'outings', item:'After Dark · two admission demo quote', description:'An adults-only evening exploring science, art, and hands-on exhibits.', base_price_cents:6000, price_kind:'demo_quote', source_url:'https://www.exploratorium.edu/visit/calendar/after-dark', source_date, facts:['After Dark is for adults 18+ at Pier 15.','Published Thursday program runs 6–10 p.m.; verify a specific event before visiting.','Two-person price is a simulated quote; live tickets and add-ons are not verified.'], tags:['science','hands-on','art','evening','waterfront'], code:'EXPLORATORIUM-DEMO' },
  { id:'cal-academy', name:'California Academy', initials:'CA', color:'#87bca5', scenario:'outings', item:'NightLife · two admission demo quote', description:'An evening of science and culture at the California Academy of Sciences.', base_price_cents:6000, price_kind:'demo_quote', source_url:'https://www.calacademy.org/nightlife', source_date, facts:['NightLife requires age 21+ and physical photo ID.','Runs selected Thursdays, 6–10 p.m.; not every Thursday.','Two-person quote is simulated. Planetarium admission is separate; availability unverified.'], tags:['science','culture','museum','evening','nature'], code:'ACADEMY-DEMO' },
  { id:'sfmoma', name:'SFMOMA', initials:'SF', color:'#ed7257', scenario:'outings', item:'Museum visit · two admission demo quote', description:'Modern and contemporary art at 151 Third Street.', base_price_cents:6000, price_kind:'demo_quote', source_url:'https://www.sfmoma.org/visit/', source_date, facts:['Modern and contemporary art museum at 151 Third Street.','Published Thursday opening hours are noon–8 p.m.','Two-person quote is simulated; no dated exhibition or live availability is promised.'], tags:['art','modern','contemporary','museum','soma'], code:'SFMOMA-DEMO' },
];

export const scenarios: Scenario[] = [
  {id:'dating',name:'A coffee date',publisher_id:'wavelength',app_name:'Wavelength',subtitle:'A connection, then a place to meet.',prompt:'We matched and want somewhere in SF for a casual coffee date.',preferences:['Coffee for two','San Francisco','Casual first date'],brand_ids:['blue-bottle','sightglass','ritual']},
  {id:'fashion',name:'Everyday sneakers',publisher_id:'wardrobe',app_name:'Thread',subtitle:'Personal style, negotiated for you.',prompt:'Find everyday women’s sneakers for walking around SF; I care about comfort and easy cleaning.',preferences:['Everyday walking','Comfort','Easy cleaning'],brand_ids:['allbirds','rothys','everlane']},
  {id:'outings',name:'An evening out',publisher_id:'cityguide',app_name:'Roam',subtitle:'Something worth going out for.',prompt:'Help us choose an interesting SF outing; we like art and hands-on science.',preferences:['San Francisco','Art','Hands-on science'],brand_ids:['exploratorium','cal-academy','sfmoma']},
];

/** Fictional campaign policies. No merchant has authorized these bids or offers. */
export function createCampaigns(): Campaign[] {
  const policies: Record<string, [number, number, string]> = {
    'blue-bottle':[180,200,'Premium: prioritize publisher reach with a strong CPC, protect price, and use limited discounts only when needed.'],
    sightglass:[125,650,'Flexible: preserve CPC efficiency and compete through customer savings; improve discounts when losing.'],
    ritual:[145,450,'Balanced: offer modest initial customer value, then respond to the leading effective price.'],
    allbirds:[200,2500,'Premium: protect product value and respond conservatively to competing customer offers.'],
    rothys:[160,4500,'Flexible: compete with meaningful customer savings while maintaining a moderate CPC.'],
    everlane:[240,800,'Balanced: emphasize the existing sale value; respect the additional discount ceiling.'],
    exploratorium:[170,1600,'Flexible: use customer savings to compete with other cultural outings.'],
    'cal-academy':[220,1000,'Balanced: protect admission value while offering a measured customer discount.'],
    sfmoma:[250,600,'Premium: maintain a strong CPC and limited additional admission discounts.'],
  };
  return brands.map(brand => ({brand_id:brand.id,version:1,active:true,max_cpc_cents:policies[brand.id][0],max_discount_cents:policies[brand.id][1],strategy:policies[brand.id][2],balance_cents:10000,reserved_cents:0,spent_cents:0}));
}
