import { useEffect, useRef, useState } from 'react';
import { AnimatePresence, LayoutGroup, MotionConfig, motion, useReducedMotion } from 'motion/react';
import { AnimatedValue, LeadChange, RoundStage } from './AuctionMotion';
import PaymentReceipt from './PaymentReceipt';
import { ArrowUpRight, ArrowRight, Check, ChevronDown, CircleHelp, Coffee, Compass, ExternalLink, Heart, Layers3, Play, Pause, Plus, RotateCcw, Settings2, ShieldCheck, ShoppingBag, Sparkles, Square, X, Zap } from 'lucide-react';
import type { Auction, Bootstrap, Brand, Campaign, LedgerEntry, RankedOffer, ScenarioId } from '../shared/types';

const money = (n = 0) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(n / 100);
const statusText = (s:string) => s.replaceAll('_', ' ');
const active = (a:Auction|null) => !!a && ['assessing','running','paused'].includes(a.status);
const iconFor = (s:ScenarioId) => s === 'dating' ? <Heart size={16}/> : s === 'fashion' ? <ShoppingBag size={16}/> : <Compass size={16}/>;
async function api<T>(path:string, options:RequestInit = {}):Promise<T> {
  const token = sessionStorage.getItem('accord-admin-token');
  const workspace = new URLSearchParams(window.location.search).get('workspace');
  const r = await fetch(path, { ...options, headers: { 'Content-Type':'application/json', ...(token ? {'x-admin-token':token} : {}), ...(workspace ? {'x-demo-workspace':workspace} : {}), ...options.headers } });
  let data: {error?:string; message?:string};
  try { data = await r.json() as typeof data; } catch { throw new Error('The exchange server is not reachable yet. Check the connection and retry.'); }
  if (!r.ok) throw new Error(data.error || data.message || `Request failed (${r.status})`);
  return data as T;
}
type PresentationBootstrap = Bootstrap & { presentation?: { workspace_id:string; consumers:Partial<Record<ScenarioId,string>> } };
const post = <T,>(path:string,body:unknown) => api<T>(path, {method:'POST',body:JSON.stringify(body)});

export default function App() {
  const reduceMotion=useReducedMotion();
  const modalRef=useRef<HTMLElement>(null);
  const [data,setData] = useState<PresentationBootstrap|null>(null);
  const [tab,setTab] = useState<'exchange'|'studio'|'ledger'>('exchange');
  const [scenario,setScenario] = useState<ScenarioId>('dating');
  const [intent,setIntent] = useState('');
  const [auction,setAuction] = useState<Auction|null>(null);
  const [mode,setMode] = useState<'live'|'simulation'>('simulation');
  const [paymentMode,setPaymentMode] = useState<'sandbox'|'simulation'>('simulation');
  const [followup,setFollowup] = useState('');
  const [busy,setBusy] = useState(false);
  const [error,setError] = useState('');
  const [fundingNotice,setFundingNotice]=useState(()=>new URLSearchParams(window.location.search).get('funding')==='success');
  const [replay,setReplay] = useState(false);
  const [replayRound,setReplayRound] = useState(0);
  const [settings,setSettings] = useState(false);
  useEffect(()=>{if(!settings)return;const previous=document.activeElement as HTMLElement|null;const focusTimer=requestAnimationFrame(()=>modalRef.current?.querySelector<HTMLInputElement>('input')?.focus());const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape'){setSettings(false);return;}if(e.key==='Tab'){const items=Array.from(modalRef.current?.querySelectorAll<HTMLElement>('button,input,[href]')||[]);const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',onKey);return()=>{cancelAnimationFrame(focusTimer);document.removeEventListener('keydown',onKey);previous?.focus();};},[settings]);
  const [token,setToken] = useState(sessionStorage.getItem('accord-admin-token') || '');
  const [historyOpen,setHistoryOpen] = useState(false);
  const [explain,setExplain] = useState(false);
  const [composer,setComposer] = useState(false);
  const observerState=useRef({replay:false,composer:false,auction:null as Auction|null});
  observerState.current={replay,composer,auction};
  const initial = useRef(true);
  const linkedAuction=useRef<{id:string|null;completedIds:Set<string>|null}>({id:new URLSearchParams(window.location.search).get('auction'),completedIds:null});
  const clearLinkedAuction=()=>{linkedAuction.current={id:null,completedIds:null};const url=new URL(window.location.href);if(url.searchParams.has('auction')){url.searchParams.delete('auction');window.history.replaceState(null,'',url);}};
  const exchangeRef = useRef<HTMLDivElement>(null);
  const focusExchange = () => requestAnimationFrame(()=>exchangeRef.current?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'}));
  const refresh = async () => {
    const requestedWorkspace=new URLSearchParams(window.location.search).get('workspace');
    let d = await api<PresentationBootstrap>('/api/bootstrap');
    if(!requestedWorkspace&&d.presentation?.workspace_id){const url=new URL(window.location.href);url.searchParams.set('workspace',d.presentation.workspace_id);window.history.replaceState(null,'',url);d=await api<PresentationBootstrap>('/api/bootstrap');}
    setData(d);
    const state=observerState.current;
    if(initial.current){setError('');setIntent(d.scenarios[0]?.prompt||'');setScenario(d.scenarios[0]?.id||'dating');setMode(d.capabilities.live_agents?'live':'simulation');initial.current=false;}
    if(!state.replay&&!state.composer){
      const recent=d.auctions.filter(a=>!a.id.startsWith('recorded:')).sort((a,b)=>Date.parse(b.created_at)-Date.parse(a.created_at));
      let incoming=recent.find(a=>active(a)) || recent.find(a=>a.status==='completed') || recent[0];
      const linked=recent.find(a=>a.id===linkedAuction.current.id);
      if(linked){
        if(active(linked)){incoming=linked;}
        else if(!linkedAuction.current.completedIds){linkedAuction.current.completedIds=new Set(recent.map(a=>a.id));incoming=linked;}
        else {const newer=recent.find(a=>!linkedAuction.current.completedIds!.has(a.id));if(newer){clearLinkedAuction();incoming=newer;}else{incoming=linked;}}
      }
      if(incoming){
        const same=state.auction?.id===incoming.id;
        const stale=same&&Date.parse(incoming.updated_at)<Date.parse(state.auction!.updated_at);
        if(!stale){setAuction(incoming);setScenario(incoming.scenario);setIntent(incoming.intent);setMode(incoming.mode);setPaymentMode(incoming.payment_mode||'simulation');}
      }
    }
    return d;
  };
  useEffect(()=>{
    let stopped=false,fetching=false;
    const sync=async()=>{if(fetching||stopped)return;fetching=true;try{await refresh();}catch(e){if(!stopped)setError((e as Error).message);}finally{fetching=false;}};
    sync(); const timer=setInterval(sync,1000);
    return()=>{stopped=true;clearInterval(timer);};
  },[]);
  const s = data?.scenarios.find(x=>x.id===scenario);
  const brands = data?.brands.filter(b=>b.scenario===scenario) || [];
  const latest = auction?.rounds.at(-1);
  const round = replay ? auction?.rounds[replayRound] : latest;
  const leader = round?.offers.find(o=>o.brand_id===round.leader_id);
  const winner = replay ? (replayRound === (auction?.rounds.length || 0)-1 ? auction?.winner : undefined) : auction?.winner;
  const cashLeader = round?.offers.find(o=>o.brand_id===round.cash_leader_id);
  const selected = winner || leader;
  const chosenBrand = data?.brands.find(b=>b.id===selected?.brand_id);
  const receipt = data?.ledger.find(l=>l.auction_id===auction?.id && l.kind==='click');
  const consumerUrl=data?.presentation?.consumers[scenario];
  const transfer = data?.ledger.find(l=>l.auction_id===auction?.id && l.kind==='transfer');
  const chooseScenario = (id:ScenarioId) => { if(active(auction) && !replay) return; setScenario(id);setIntent(data?.scenarios.find(x=>x.id===id)?.prompt || '');setAuction(null);sessionStorage.removeItem('accord-current-auction');setReplay(false);setFollowup('');setError(''); };
  const run = async (nextIntent?:string) => { const requestIntent=nextIntent || intent; if(!requestIntent.trim() || !s)return;setBusy(true);setError('');setReplay(false);try {const created=await post<Auction>(`/api/demo/${scenario}/auctions`, {intent:requestIntent,preferences:s.preferences,mode,payment_mode:paymentMode,target_score:85,max_rounds:5});clearLinkedAuction();setAuction(created);setComposer(false);observerState.current={...observerState.current,composer:false,auction:created};setIntent(requestIntent);setFollowup('');sessionStorage.setItem('accord-current-auction',created.id);focusExchange();}catch(e){setError((e as Error).message);}finally{setBusy(false);} };
  const action = async (action:string) => { if(!auction)return;setBusy(true);setError('');try{setAuction(await post<Auction>(`/v1/auctions/${auction.id}/actions`,{action}));await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);} };
  const click = async () => {if(!auction?.placement || replay)return;setBusy(true);try{const result=await post<{placement:NonNullable<Auction['placement']>; destination:string}>(`/v1/placements/${auction.placement.id}/click`,{});setAuction({...auction,placement:result.placement});await refresh();window.open(result.destination,'_blank','noopener,noreferrer');}catch(e){setError((e as Error).message);}finally{setBusy(false);} };
  const loadReplay = (a:Auction) => {setAuction(a);setScenario(a.scenario);setIntent(a.intent);setReplay(true);setComposer(false);observerState.current={replay:true,composer:false,auction:a};setReplayRound(0);setHistoryOpen(false);setTab('exchange');focusExchange();};

  return <MotionConfig reducedMotion="user"><div className={`shell ${auction&&!composer&&tab==='exchange'?'has-auction':''}`}>
    <aside className="rail"><a className="logo-mark" href="#" aria-label="Accord home" onClick={()=>setTab('exchange')}>a<span>↗</span></a><div className="rail-line"/><button className={tab==='exchange'?'active':''} onClick={()=>setTab('exchange')} title="Exchange"><Layers3 size={21}/></button><button className={tab==='studio'?'active':''} onClick={()=>setTab('studio')} title="Brand studio"><Sparkles size={21}/></button><button className={tab==='ledger'?'active':''} onClick={()=>{setTab('ledger');refresh().catch(e=>setError(e.message));}} title="Transactions"><ArrowUpRight size={22}/></button><div className="rail-spacer"/><button onClick={()=>setSettings(true)} title="Connection settings"><Settings2 size={20}/></button><div className="avatar">A</div></aside>
    <div className="workspace"><header className="topbar"><div className="wordmark">accord<span> / </span><span className="wordmark-sub">agent exchange</span></div><div className="topbar-right"><button className="icon-btn connection-button" title="Connection settings" aria-label="Connection settings" onClick={()=>setSettings(true)}><Settings2 size={16}/></button><span className="demo-dot"/> HACKATHON DEMO <span className="topbar-divider"/><span>San Francisco, CA</span><button className="icon-btn help" title="How the exchange works" onClick={()=>setExplain(!explain)}><CircleHelp size={17}/></button></div></header>
      <main>
        <div className="page-heading"><div><div className="eyebrow">THE BETTER OFFER WINS.</div><h1>{tab==='exchange'?<>A better offer.<br/><span>By negotiation.</span></>:tab==='studio'?<>Meet the<br/><span>other side.</span></>:<>Follow<br/><span>the value.</span></>}</h1><p>{tab==='exchange'?'Brands compete. Your agent negotiates. You get the better deal.':tab==='studio'?'Nine brand agents. Different strategies. One shared exchange.':'Every offer, click, and settlement leaves a clear trail.'}</p></div><button className="button secondary history-btn" onClick={()=>setHistoryOpen(!historyOpen)}><RotateCcw size={15}/> Auction history <ChevronDown size={14}/></button></div>
        {explain && <div className="explanation"><div><b>Advertising money doesn’t buy a better score.</b><p>The user agent scores fit (60%) and effective price (40%). The advertising bid only breaks an exact tie. Agents can revise, hold, finalize, or withdraw for up to five rounds.</p></div><button className="icon-btn" aria-label="Close scoring explanation" onClick={()=>setExplain(false)}><X size={18}/></button></div>}
        {historyOpen && <div className="history-panel"><div className="section-title"><span>RECORDED AUCTIONS</span><span>Read-only replay · no billing</span></div>{data?.auctions.filter(a=>!active(a)).length ? data.auctions.filter(a=>!active(a)).map(a=><button key={a.id} onClick={()=>loadReplay(a)}><span>{iconFor(a.scenario)} {data.scenarios.find(s=>s.id===a.scenario)?.app_name} <b>{a.intent}</b></span><small>{a.id.startsWith('recorded:')?'Recorded live GPT · Sep 28':`${a.rounds.length} rounds · ${statusText(a.status)} · ${a.mode}`}</small><Play size={15}/></button>) : <p>No completed auctions yet. Run an exchange to create a replay.</p>}</div>}
        {fundingNotice&&<div className="funding-confirmation" role="status"><Check size={16}/><div><b>Checkout completed.</b><span>Funds appear after Stripe confirms payment.</span></div><button className="icon-btn" aria-label="Dismiss checkout confirmation" onClick={()=>{setFundingNotice(false);const url=new URL(window.location.href);url.searchParams.delete('funding');window.history.replaceState(null,'',url);}}><X size={15}/></button></div>}
        {error && <div className="error" role="alert"><span>{error}</span><button className="icon-btn" aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}
        {!data ? <div className="loading-panel"><div className="spinner"/><h2>Connecting to the exchange</h2><p>Your workspace will appear here.</p><button className="button secondary" onClick={()=>refresh().catch(e=>setError(e.message))}>Retry connection</button></div> : <>
        <nav className="tabs"><button className={tab==='exchange'?'selected':''} onClick={()=>setTab('exchange')}>Exchange <span>01</span></button><button className={tab==='studio'?'selected':''} onClick={()=>setTab('studio')}>Brand studio <span>02</span></button><button className={tab==='ledger'?'selected':''} onClick={()=>{setTab('ledger');refresh().catch(e=>setError(e.message));}}>Transactions <span>03</span></button><div className="tabs-right"><span className={`status-dot ${data.capabilities.live_agents?'green':''}`}/>{data.capabilities.live_agents?'Live agents connected':'Live agents not configured'}</div></nav>
        {tab==='exchange' && <>
          <div className="consumer-links"><div><span className="status-dot green"/><span>CONNECTED CONSUMER APPS</span></div>{data.scenarios.map(sc=>{const url=data.presentation?.consumers[sc.id];return url?<a key={sc.id} href={url} target="_blank" rel="noreferrer">{iconFor(sc.id)}<span>{sc.app_name}</span><ArrowUpRight size={13}/></a>:<span className="consumer-link-pending" key={sc.id}>{iconFor(sc.id)}{sc.app_name}<small>connecting</small></span>;})}<span className="stage-id">STAGE {data.presentation?.workspace_id?.slice(0,12)||new URLSearchParams(window.location.search).get('workspace')?.slice(0,12)||'shared'}</span></div>
          <div className="exchange-toolbar observer-toolbar"><div className="observer-status"><span className={`status-dot ${replay?'':'green'}`}/>{replay?'Inspecting recorded decisions':'Listening for requests from consumer agents'}<small>{replay?'Read-only replay':'Auto-updates every second'}</small></div>{auction&&active(auction)&&!replay&&<div className="auction-controls top-auction-controls">{auction.status==='paused'?<button disabled={busy} onClick={()=>action('continue')}><Play size={12}/>Continue</button>:<button disabled={busy||auction.pause_requested} onClick={()=>action('pause')}><Pause size={12}/>{auction.pause_requested?'Pausing…':'Pause'}</button>}<button disabled={busy||!latest?.offers.length} onClick={()=>action('accept')}><Check size={12}/>Accept current best</button><button disabled={busy} onClick={()=>action('cancel')} aria-label="Cancel current auction"><Square size={11}/></button></div>}<button className="button secondary test-toggle" disabled={active(auction)&&!replay} onClick={()=>{setComposer(!composer);observerState.current.composer=!composer;}}>{composer?<X size={13}/>:<Plus size={13}/>} {composer?'Close test request':'Start test request'}</button></div>
          {composer&&<div className="exchange-toolbar test-toolbar"><div className="scenario-switch">{data.scenarios.map(sc=><button disabled={active(auction)&&!replay} className={scenario===sc.id?'selected':''} onClick={()=>chooseScenario(sc.id)} key={sc.id}>{iconFor(sc.id)}{sc.name}</button>)}</div><div className="mode-control"><span>AGENT MODE</span><select value={mode} disabled={active(auction)&&!replay} aria-label="Agent mode" onChange={e=>{setMode(e.target.value as typeof mode);if(e.target.value==='simulation')setPaymentMode('simulation');}}><option value="simulation">Simulation</option><option value="live" disabled={!data.capabilities.live_agents}>Live GPT {!data.capabilities.live_agents?'— unavailable':''}</option></select></div><div className="mode-control"><span>FUNDS</span><select aria-label="Payment mode" value={paymentMode} disabled={active(auction)&&!replay||mode==='simulation'} onChange={e=>setPaymentMode(e.target.value as typeof paymentMode)}><option value="simulation">Simulated funds</option><option value="sandbox" disabled={!data.capabilities.stripe}>Stripe sandbox {!data.capabilities.stripe?'— unavailable':''}</option></select></div></div>}
          <div className={`mode-banner ${replay?'replay':''}`}><span>{replay?<RotateCcw size={15}/>:mode==='simulation'?<Layers3 size={15}/>:<Zap size={15}/>}</span><b>{replay?'READ-ONLY REPLAY':mode==='simulation'?'RULE-BASED SIMULATION · SIMULATED FUNDS':`LIVE GPT AGENTS · ${(active(auction)?auction?.payment_mode:paymentMode)==='sandbox'?'SANDBOX FUNDS':'SIMULATED FUNDS'}`}</b><p>{replay?auction?.id.startsWith('recorded:')?'Recorded live GPT · September 28. Original agent decisions; no billing.':'Previously recorded decisions. No offers or payments can be changed.':mode==='simulation'?'Real exchange logic with simulated decisions and credits. Live mode requires an OpenAI key.':'Brand agents independently negotiate. All campaign offers and discounts are fictional.'}</p>{replay?<button className="return-live" onClick={()=>{clearLinkedAuction();setReplay(false);observerState.current.replay=false;refresh().catch(e=>setError(e.message));}}>Return to live<ArrowRight size={12}/></button>:<span className="round-cap">MAX 5 ROUNDS</span>}</div>
          <div className="exchange-grid" ref={exchangeRef}>
            {composer?<section className="consumer-panel"><div className="section-title"><span>01 / CONSUMER APP</span><span className="tiny-pill">DEMO</span></div><div className={`consumer-app-icon ${scenario}`}>{iconFor(scenario)}</div><h2>{s?.app_name}</h2><p className="consumer-sub">{s?.subtitle}</p><div className="chat-intro"><div className="mini-avatar">{scenario==='dating'?'W':scenario==='fashion'?'S':'C'}</div><p>{scenario==='dating'?"You’ve found your person. Let’s find your place.":scenario==='fashion'?"Let’s find something that fits your everyday.":"Your next good day starts with a little discovery."}</p></div><label className="request-label" htmlFor="intent">WHAT ARE YOU LOOKING FOR?</label><textarea id="intent" value={intent} onChange={e=>setIntent(e.target.value)} disabled={active(auction)&&!replay} rows={4}/><div className="preference-list">{s?.preferences.map(p=><span key={p}>{p}</span>)}</div><button className="button primary start-button" disabled={busy||active(auction)&&!replay||mode==='live'&&!data.capabilities.live_agents||!intent.trim()} onClick={()=>run()}>{busy&&!auction?<span className="spinner small"/>:<Sparkles size={15}/>} {auction&&!active(auction)?'Start a new exchange':'Find my best offer'}<ArrowRight size={16}/></button><div className="consumer-foot"><ShieldCheck size={13}/> Only this request is shared with brand agents.</div>
              {winner && chosenBrand && <div className="recommendation"><div className="eyebrow">YOUR AGENT FOUND A MATCH</div><h3>{winner.brand_name}</h3><p>{chosenBrand.item}</p><div className="rec-price"><s>{money(winner.base_price_cents)}</s><strong>{money(winner.effective_price_cents)}</strong><span>with your offer</span></div><div className="coupon"><span>YOUR DEMO CODE</span><b>{chosenBrand.code}</b></div><button className="button primary" disabled={replay||busy||auction?.placement?.status==='expired'} onClick={click}>{auction?.placement?.status==='clicked'?'Visit again':`View ${scenario==='fashion'?'product':'experience'}`}<ArrowUpRight size={16}/></button><small>Illustrative code · no redemption. {replay?'Billing disabled during replay.':auction?.placement?.status==='clicked'?'Click recorded. Repeat visits are not charged.':''}</small></div>}
              {auction&&!active(auction)&&!replay&&<form className="followup-form" onSubmit={e=>{e.preventDefault();if(followup.trim())run(`${intent}\n\nFollow-up preference: ${followup.trim()}`);}}><label htmlFor="followup">KEEP THE CONVERSATION GOING</label><textarea id="followup" placeholder="What if we want somewhere more casual?" value={followup} onChange={e=>setFollowup(e.target.value)} rows={2}/><button className="button secondary" disabled={busy||!followup.trim()} type="submit">Ask your agent<ArrowRight size={14}/></button><small>Your follow-up starts a new exchange with the conversation context.</small></form>}
            </section>:<motion.aside key={auction?.id||'waiting'} initial={{opacity:0,x:reduceMotion?0:-12}} animate={{opacity:1,x:0}} transition={{duration:reduceMotion?0:.45,ease:[.22,1,.36,1]}} className="incoming-panel"><div className="section-title"><span>01 / REQUEST ORIGIN</span><span className="tiny-pill">{auction?'RECEIVED':'LISTENING'}</span></div><div className={`consumer-app-icon ${scenario}`}>{iconFor(scenario)}</div><h2>{auction?s?.app_name:'Awaiting intent.'}</h2><p className="incoming-intro">{auction?'An independent consumer agent submitted this opportunity to Accord.':'Open a consumer app above. Its agent will send a request here when you ask for a recommendation.'}</p><div className="incoming-request"><span>USER INTENT</span><p>{auction?auction.intent:'Your next recommendation starts in a consumer app.'}</p></div>{auction&&<><div className="preference-list">{auction.preferences.map(p=><span key={p}>{p}</span>)}</div><dl className="request-meta"><div><dt>Publisher</dt><dd>{auction.publisher_id}</dd></div><div><dt>Request</dt><dd>{auction.id.slice(0,12)}</dd></div><div><dt>Received</dt><dd>{new Date(auction.created_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</dd></div></dl></>}{consumerUrl&&<a className="button secondary full-width" href={consumerUrl} target="_blank" rel="noreferrer">Open {s?.app_name}<ArrowUpRight size={14}/></a>}<div className="request-contract"><ArrowRight size={13}/><span>Consumer intent in.<br/>Negotiated offer out.</span></div>{winner&&<div className="returned-offer"><span>RETURNED TO CONSUMER</span><h3>{winner.brand_name}</h3><b>{money(winner.effective_price_cents)}</b><small>{money(winner.discount_cents)} off · {chosenBrand?.code}</small></div>}</motion.aside>}
            <div className="exchange-main"><section className="auction-top"><div><div className="eyebrow">02 / THE NEGOTIATION</div><h2>{!auction?'Waiting for consumer intent.':auction.status==='assessing'?'Your agent is finding the fit.':winner?'A better offer, agreed.':auction.status==='failed'?'The exchange needs a retry.':auction.status==='cancelled'?'Exchange cancelled.':auction.status==='completed'?'Exchange complete.':`Let the offers do the talking.`}</h2></div><span className={`auction-status ${active(auction)&&auction?.status!=='paused'?'in-progress':''}`}><span className="status-dot"/>{replay?'Replay':auction?statusText(auction.status):'Ready to negotiate'}</span></section>
              <RoundStage auction={auction} round={round} replay={replay}/><LeadChange auction={auction} round={round}/><div className="scoring-strip"><div className="scoring-icon"><Sparkles size={17}/></div><span>YOUR AGENT’S PRIORITIES</span><b>60% <small>personal fit</small></b><span className="plus">+</span><b>40% <small>better price</small></b><button className="icon-btn" title="Scoring policy" onClick={()=>setExplain(!explain)}><CircleHelp size={14}/></button></div>
              <LayoutGroup id={auction?.id||'waiting'}><div className="brand-grid">{brands.map((brand,i)=>{const bidder=auction?.bidders.find(b=>b.brand.id===brand.id);const offer=round?.offers.find(o=>o.brand_id===brand.id);const isLeader=round?.leader_id===brand.id;const actionValue=round?.actions[brand.id] || auction?.rounds.slice(0,round?.number || 0).reverse().map(r=>r.actions[brand.id]).find(Boolean);const actionExplanation=typeof actionValue==='object'?actionValue.explanation:typeof actionValue==='string'?actionValue:undefined;return <BrandCard key={`${auction?.id||'waiting'}-${brand.id}`} brand={brand} index={i} offer={offer} previousOffer={round&&round.number>1?auction?.rounds[round.number-2]?.offers.find(o=>o.brand_id===brand.id):undefined} offerRound={round?.number} sealed={auction?.status==='running'&&!!auction.round_started_at&&!replay&&!bidder?.finalized&&!bidder?.withdrawn} fit={auction?.status==='assessing'?undefined:bidder?.fit.score} fitExplanation={auction?.status==='assessing'?undefined:bidder?.fit.explanation} leader={isLeader} winner={winner?.brand_id===brand.id} running={!!auction&&['assessing','running'].includes(auction.status)&&!replay} explanation={actionExplanation||bidder?.fit.explanation} action={offer?.finalized?'finalized':typeof actionValue==='object'?actionValue.action:actionValue} withdrawn={replay?(typeof actionValue==='object'&&actionValue.action==='withdraw'):bidder?.withdrawn}/>;})}</div></LayoutGroup>
              <section className="timeline"><div className="timeline-heading"><div className="section-title"><span>THE OFFER TIMELINE</span><span>{round?`ROUND ${round.number} OF ${auction?.max_rounds}`:'UP TO 5 ROUNDS'}</span></div>{auction&&active(auction)&&!replay&&<div className="auction-controls">{auction.status==='paused'?<button disabled={busy} onClick={()=>action('continue')}><Play size={13}/> Continue</button>:<button disabled={busy||auction.pause_requested} onClick={()=>action('pause')}><Pause size={13}/>{auction.pause_requested?'Pausing…':'Pause'}</button>}<button disabled={busy||!latest?.offers.length} onClick={()=>action('accept')}><Check size={13}/> Accept best</button><button disabled={busy} onClick={()=>action('cancel')} title="Cancel auction"><Square size={12}/></button></div>}</div><div className="round-track">{Array.from({length:5},(_,i)=>{const r=auction?.rounds[i];const changedLeader=i>0&&r?.leader_id&&r.leader_id!==auction?.rounds[i-1]?.leader_id;return <button key={i} className={`round-node ${r?'complete':''} ${round?.number===i+1?'current':''} ${changedLeader?'lead-changed':''}`} disabled={!replay||!r} onClick={()=>setReplayRound(i)}><span className="round-circle">{r?<Check size={15}/>:i+1}</span><b>Round {i+1}</b><small>{r?changedLeader?'New leader':r.offers.find(o=>o.brand_id===r.leader_id)?.brand_name||'No offer':auction?.current_round===i+1&&active(auction)?auction?.status==='paused'?'Paused':auction?.round_started_at?'In progress':'Preparing':'Awaiting offers'}</small></button>;})}</div><div className="agent-feedback"><Sparkles size={14}/><p>{round?.feedback||'Your agent will assess personal fit, compare prices, and ask brands for a better offer.'}</p></div>{auction?.end_reason&&<div className="end-reason"><Check size={12}/> Ended after {auction.rounds.length} {auction.rounds.length===1?'round':'rounds'} · {statusText(auction.end_reason)}{replay&&' · Select a completed round to inspect it'}</div>}{auction?.error&&<p className="inline-error">{auction.error}</p>}</section>
              <section className={`comparison ${selected&&cashLeader&&selected.brand_id!==cashLeader.brand_id?'value-won':''}`}><div className="comparison-title"><div className="eyebrow">THE DIFFERENCE IS THE DEAL</div><h3>{selected&&cashLeader&&selected.brand_id!==cashLeader.brand_id?'Less ad spend. More user value.':'A recommendation worth competing for.'}</h3><p>{selected&&cashLeader&&selected.brand_id!==cashLeader.brand_id?`${selected.brand_name} leads on user value, even though ${cashLeader.brand_name} offers more for the click.`:'The highest advertising bid and the best customer offer are two different things.'}</p></div><div className="comparison-stat"><small>HIGHEST CASH BID</small><strong>{cashLeader?money(cashLeader.bid_cents):'—'}</strong><span>{cashLeader?.brand_name||'Waiting for offers'}</span></div><div className="comparison-stat user"><small>USER VALUE LEADER</small><strong>{selected?money(selected.bid_cents):'—'}<em>{selected?'CPC':''}</em></strong><span>{selected?.brand_name||'Chosen by your agent'}</span>{selected&&<span className="customer-price">Customer pays <b>{money(selected.effective_price_cents)}</b></span>}</div></section>
              {auction?.placement&&!replay&&<PaymentReceipt auction={auction} receipt={receipt} transfer={transfer} transfers={data.ledger.filter(l=>l.auction_id===auction.id&&l.kind==='transfer')}/>}

            </div>
          </div>
        </>}
        {tab==='studio'&&<div className="studio"><div className="studio-intro"><div><h2>Give every brand a point of view.</h2><p>Configure the limits. Let the agents decide how to compete. Changes apply to new auctions.</p></div><span className="outline-pill">{data.brands.length} RESEARCHED TEMPLATES</span></div><div className="studio-grid">{data.brands.map(b=><CampaignCard key={b.id} brand={b} campaign={data.campaigns.find(c=>c.brand_id===b.id)!} stripe={data.capabilities.stripe} onRefresh={refresh} onError={setError}/>)}</div></div>}
        {tab==='ledger'&&<Ledger ledger={data.ledger} brands={data.brands} stripe={data.capabilities.stripe}/>}
        <footer><span><span className="small-wordmark">accord</span> Better deals, by design.</span><p>Prototype · Real brands, fictional campaigns & discounts · No merchant affiliation · No coupon redemption</p><span>BUILT FOR AGENT COMMERCE ↗</span></footer>
        </>}
      </main>
    </div>
    {settings&&<div className="modal-overlay" onClick={()=>setSettings(false)}><section ref={modalRef} role="dialog" aria-modal="true" aria-labelledby="connection-title" className="modal" onClick={e=>e.stopPropagation()}><div className="section-title"><span>CONNECTION SETTINGS</span><button className="icon-btn" aria-label="Close connection settings" onClick={()=>setSettings(false)}><X size={18}/></button></div><h2 id="connection-title">Connect your workspace.</h2><p>If your server requires an admin token, enter it here. It stays in this browser session and is sent only to this application.</p><label>Admin token<input type="password" value={token} onChange={e=>setToken(e.target.value)} autoComplete="off"/></label><button className="button primary" onClick={()=>{sessionStorage.setItem('accord-admin-token',token);setSettings(false);setError('');refresh().catch(e=>setError(e.message));}}>Save connection<ArrowRight size={16}/></button></section></div>}
  </div></MotionConfig>;
}

function BrandCard({brand,index,offer,previousOffer,offerRound,sealed,fit,fitExplanation,leader,winner,running,explanation,action,withdrawn}:{brand:Brand;index:number;offer?:RankedOffer;previousOffer?:RankedOffer;offerRound?:number;sealed:boolean;fit?:number;fitExplanation?:string;leader:boolean;winner:boolean;running:boolean;explanation?:string;action?:string;withdrawn?:boolean}) {
  const reduced=useReducedMotion();
  const discountChange=offer&&previousOffer?offer.discount_cents-previousOffer.discount_cents:0;
  return <motion.article layout="position" initial={{opacity:0,y:reduced?0:16}} animate={{opacity:withdrawn?.55:1,y:0}} transition={{duration:reduced?0:.35,delay:reduced?0:index*.07,ease:[.22,1,.36,1]}} className={`brand-card ${leader?'leader':''} ${withdrawn?'withdrawn':''} ${sealed?'sealed':''}`}>
    {leader&&<motion.div layoutId="current-leader" transition={{type:'spring',stiffness:280,damping:32,duration:reduced?0:undefined}} className="leader-marker"/>}
    <div className="brand-card-top"><span className="brand-number">[0{index+1}]</span>{leader?<span className="leader-badge"><span/> {winner?'SELECTED':sealed?'PUBLIC LEADER':'LEADING OFFER'}</span>:<span className="brand-state">{withdrawn?'WITHDRAWN':action?statusText(action).toUpperCase():running?'EVALUATING':'BRAND AGENT'}</span>}</div>
    <div className="brand-identity"><div className="brand-monogram" style={{background:brand.color}}>{brand.initials}</div><div><h3>{brand.name}</h3><span>{brand.item}</span></div></div>
    <div className={`agent-working ${sealed?'active':''}`} aria-live="polite">{sealed?<><span className="sealed-dots" aria-hidden="true"><i/><i/><i/></span><span>Negotiating privately</span><LockLabel/></>:offer?.finalized?<><Check size={11}/><span>Final offer held</span></>:withdrawn?<><Square size={10}/><span>Left the auction</span></>:<><span className="quiet-dot"/><span>{offer?`Round ${offerRound} · public offer`:running?'Assessing personal fit':'Waiting for a request'}</span></>}</div>
    <div className="brand-price"><small>{sealed&&offer?`LAST PUBLIC PRICE · ROUND ${offerRound}`:'YOUR EFFECTIVE PRICE'}</small><div><strong><AnimatedValue value={offer?money(offer.effective_price_cents):money(brand.base_price_cents)}/></strong>{!!offer?.discount_cents&&<s>{money(brand.base_price_cents)}</s>}</div><span className="quote-label">{brand.price_kind==='demo_quote'?'Simulated quote':'Dated catalog snapshot'}</span></div>
    <div className="offer-pair"><div><span>Ad bid / click</span><b><AnimatedValue value={offer?money(offer.bid_cents):'—'}/></b></div><div><span>Your discount</span><b className={offer?.discount_cents?'discount':''}><AnimatedValue value={offer?`−${money(offer.discount_cents)}`:'—'}/></b></div></div>
    <div className="discount-change-slot"><AnimatePresence initial={false}>{discountChange>0&&<motion.div key={`${offerRound}-${offer?.discount_cents}`} className="discount-improved" initial={{opacity:0,y:reduced?0:5}} animate={{opacity:1,y:0}} exit={{opacity:0}} transition={{duration:reduced?0:.25}}><ArrowRight size={11}/>{money(discountChange)} more for you this round</motion.div>}</AnimatePresence></div>
    <div className="fit-row"><span>Personal fit</span><b>{fit===undefined?'—':`${fit}/100`}</b></div><div className="fit-track"><motion.span initial={false} animate={{scaleX:(fit||0)/100}} transition={{duration:reduced?0:.55,ease:[.22,1,.36,1]}}/></div>
    {fitExplanation&&<details className="fit-details"><summary>Why this fit?</summary><p>{fitExplanation}</p><small>Assessed before bids · fixed for this auction</small></details>}
    <div className="price-score-row"><span>Price score</span><b><AnimatedValue value={offer?offer.price_score.toFixed(1):'—'}/><small> / 100</small></b></div>
    <div className="score-row"><span>User value score</span><b><AnimatedValue value={offer?offer.user_score.toFixed(1):'—'}/><small> / 100</small></b></div>
    <div className="brand-explanation"><span>“</span><AnimatePresence mode="wait" initial={false}><motion.p key={explanation||brand.description} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:reduced?0:.18}}>{explanation||brand.description}</motion.p></AnimatePresence></div>
    <a className="source-link" href={brand.source_url} target="_blank" rel="noreferrer">Catalog source<ArrowUpRight size={12}/></a>
  </motion.article>;
}
function LockLabel(){return <svg aria-hidden="true" width="10" height="10" viewBox="0 0 12 12" fill="none"><rect x="2.5" y="5" width="7" height="5" stroke="currentColor"/><path d="M4 5V3a2 2 0 0 1 4 0v2" stroke="currentColor"/></svg>}

function CampaignCard({brand,campaign,stripe,onRefresh,onError}:{brand:Brand;campaign:Campaign;stripe:boolean;onRefresh:()=>Promise<unknown>;onError:(s:string)=>void}) {
  const [editing,setEditing] = useState(false);
  const [bid,setBid] = useState(String((campaign?.max_cpc_cents||0)/100));
  const [discount,setDiscount] = useState(String((campaign?.max_discount_cents||0)/100));
  const [strategy,setStrategy] = useState(campaign?.strategy||'');
  const [busy,setBusy] = useState(false);
  const save = async () => {setBusy(true);try{await api(`/v1/campaigns/${brand.id}`,{method:'PATCH',body:JSON.stringify({max_cpc_cents:Math.round(Number(bid)*100),max_discount_cents:Math.round(Number(discount)*100),strategy,active:campaign.active})});await onRefresh();setEditing(false);}catch(e){onError((e as Error).message);}finally{setBusy(false);}};
  const fund = async (simulation:boolean) => {setBusy(true);try{const r=await post<{url?:string}>(simulation?`/api/simulation/fund/${brand.id}`:`/v1/campaigns/${brand.id}/fund`,{amount_cents:10000});if(r.url)window.location.assign(r.url);else await onRefresh();}catch(e){onError((e as Error).message);}finally{setBusy(false);}};
  const toggle = async () => {setBusy(true);try{await api(`/v1/campaigns/${brand.id}`,{method:'PATCH',body:JSON.stringify({active:!campaign.active})});await onRefresh();}catch(e){onError((e as Error).message);}finally{setBusy(false);}};
  if(!campaign)return null;
  return <article className="campaign-card"><div className="brand-identity"><div className="brand-monogram" style={{background:brand.color}}>{brand.initials}</div><div><h3>{brand.name}</h3><span>{brand.scenario} · v{campaign.version}</span></div><button className={`toggle ${campaign.active?'on':''}`} aria-label={`${campaign.active?'Pause':'Activate'} ${brand.name}`} title={campaign.active?'Active':'Paused'} disabled={busy} onClick={toggle}><span/></button></div><h4>{brand.item}</h4><p>{brand.description}</p><ul className="fact-list">{brand.facts.slice(0,3).map(f=><li key={f}><Check size={12}/>{f}</li>)}</ul><a className="source-link" href={brand.source_url} target="_blank" rel="noreferrer">Catalog source · {brand.source_date}<ArrowUpRight size={12}/></a><div className="catalog-note">{brand.price_kind==='demo_quote'?'Demo quote':'Catalog snapshot'}: {money(brand.base_price_cents)} · Fictional campaign & code</div>{editing?<div className="campaign-form"><div className="form-row"><label>Max CPC ($)<input type="number" min="0.01" step="0.01" value={bid} onChange={e=>setBid(e.target.value)}/></label><label>Max discount ($)<input type="number" min="0" step="0.01" value={discount} onChange={e=>setDiscount(e.target.value)}/></label></div><label>Agent strategy<textarea value={strategy} onChange={e=>setStrategy(e.target.value)} rows={3}/></label><div className="form-row"><button className="button primary" onClick={save} disabled={busy}>Save strategy<Check size={14}/></button><button className="button secondary" onClick={()=>setEditing(false)}>Cancel</button></div></div>:<><div className="campaign-stats"><div><span>Max CPC</span><b>{money(campaign.max_cpc_cents)}</b></div><div><span>Max discount</span><b>{money(campaign.max_discount_cents)}</b></div><div><span>{stripe?'Sandbox available':'Simulated available'}</span><b>{money(campaign.balance_cents-campaign.reserved_cents)}</b></div></div><p className="strategy-preview">{campaign.strategy}</p><button className="button secondary full-width" onClick={()=>setEditing(true)}><Settings2 size={14}/> Edit campaign</button></>}<div className="fund-actions"><button disabled={busy||!stripe} onClick={()=>fund(false)} title={!stripe?'Stripe sandbox is not configured':undefined}><Plus size={13}/> $100 sandbox</button><button disabled={busy} onClick={()=>fund(true)}><Plus size={13}/> $100 simulated</button></div><small className="fund-note">Simulated credits are separate from Stripe funds.</small></article>;
}

function Ledger({ledger,brands,stripe}:{ledger:LedgerEntry[];brands:Brand[];stripe:boolean}) {
 const clicks=ledger.filter(l=>l.kind==='click');
 const sum=(key:'amount_cents'|'publisher_cents'|'network_cents',mode:'sandbox'|'simulation')=>clicks.filter(l=>l.mode===mode).reduce((a,l)=>a+(l[key]||0),0);
 const [filter,setFilter]=useState<'all'|'sandbox'|'simulation'>('all');
 return <section className="ledger"><div className="studio-intro"><div><h2>The economics, in the open.</h2><p>Selection reserves a CPC. A click charges it. The publisher earns 80%; the network earns 20%.</p></div><span className="outline-pill">{stripe?'STRIPE SANDBOX CONNECTED':'STRIPE NOT CONFIGURED'}</span></div><div className="ledger-stats">{(['amount_cents','publisher_cents','network_cents'] as const).map((key,i)=><div key={key}><span>{['ADVERTISING SPEND','PUBLISHER EARNINGS','NETWORK GROSS'][i]}</span><strong>{money(sum(key,'sandbox'))}</strong><small>Stripe sandbox</small><div className="simulation-total">{money(sum(key,'simulation'))}<small>simulated</small></div></div>)}</div><div className="ledger-table"><div className="ledger-table-heading"><h3>Transaction journal</h3><div className="scenario-switch">{(['all','sandbox','simulation'] as const).map(v=><button key={v} className={filter===v?'selected':''} onClick={()=>setFilter(v)}>{statusText(v)}</button>)}</div></div><div className="table-scroll"><table><thead><tr><th>EVENT</th><th>BRAND / PUBLISHER</th><th>AMOUNT</th><th>MODE</th><th>STATUS</th><th>TIME</th></tr></thead><tbody>{ledger.filter(l=>filter==='all'||l.mode===filter).map(l=><tr key={l.id}><td><b>{statusText(l.kind)}</b><small>{l.id.slice(0,18)}</small></td><td>{brands.find(b=>b.id===l.brand_id)?.name||l.brand_id}<small>{l.publisher_id||'Campaign balance'}</small></td><td><b>{money(l.amount_cents)}</b></td><td><span className="tiny-pill">{l.mode}</span></td><td><span className={`ledger-status ${l.status}`}>{l.status}</span>{l.error&&<small className="inline-error">{l.error}</small>}{l.stripe_id&&<small>{l.stripe_id}</small>}</td><td>{new Date(l.created_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'})}</td></tr>)}</tbody></table>{!ledger.filter(l=>filter==='all'||l.mode===filter).length&&<div className="empty-journal"><ArrowUpRight size={28}/><h3>A clear ledger starts here.</h3><p>Fund a campaign or click a winning recommendation to see the transaction trail.</p></div>}</div></div><p className="ledger-disclaimer">Sandbox transfers are not bank payouts. Processing fees are recorded separately. Demo discounts do not create cash liabilities.</p></section>;
}
