import { useEffect, useRef, useState } from 'react';
import { AnimatePresence, LayoutGroup, MotionConfig, motion, useReducedMotion } from 'motion/react';
import { AnimatedValue } from './AuctionMotion';
import { LiveOperations } from './LiveOperations';
import PaymentReceipt from './PaymentReceipt';
import ExternalBrands from './ExternalBrands';
import { ArrowUpRight, ArrowRight, Check, ChevronDown, CircleHelp, Coffee, Compass, ExternalLink, Heart, Layers3, Play, Pause, Plus, RotateCcw, Settings2, ShieldCheck, ShoppingBag, Sparkles, Square, X, Zap } from 'lucide-react';
import type { Auction, Bootstrap, Brand, Campaign, LedgerEntry, RankedOffer, ScenarioId } from '../shared/types';

const money = (n = 0) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(n / 100);
const statusText = (s:string) => s.replaceAll('_', ' ');
const active = (a:Auction|null) => !!a && ['assessing','running','paused'].includes(a.status);
const iconFor = (s:ScenarioId) => s === 'dating' ? <Heart size={16}/> : s === 'fashion' ? <ShoppingBag size={16}/> : <Compass size={16}/>;
async function api<T>(path:string, options:RequestInit = {}):Promise<T> {
  const token = sessionStorage.getItem('accord-admin-token');
  const workspace = new URLSearchParams(window.location.search).get('workspace');
  const r = await fetch(path, { ...options, headers: { 'Content-Type':'application/json', ...(token ? {'x-admin-token':token} : {}), ...(workspace ? {'x-demo-workspace':workspace} : {}), ...options.headers } });
  let data: {error?:string; message?:string};
  try { data = await r.json() as typeof data; } catch { throw new Error('The exchange server is not reachable yet. Check the connection and retry.'); }
  if (!r.ok) throw new Error(data.error || data.message || `Request failed (${r.status})`);
  return data as T;
}
type PresentationBootstrap = Bootstrap & { presentation?: { workspace_id:string; consumers:Partial<Record<ScenarioId,string>> } };
const post = <T,>(path:string,body:unknown) => api<T>(path, {method:'POST',body:JSON.stringify(body)});

export default function App() {
  const reduceMotion=useReducedMotion();
  const modalRef=useRef<HTMLElement>(null);
  const [data,setData] = useState<PresentationBootstrap|null>(null);
  const [tab,setTab] = useState<'exchange'|'studio'|'ledger'>('exchange');
  const [scenario,setScenario] = useState<ScenarioId>('dating');
  const [intent,setIntent] = useState('');
  const [auction,setAuction] = useState<Auction|null>(null);
  const [mode,setMode] = useState<'live'|'simulation'>('simulation');
  const [paymentMode,setPaymentMode] = useState<'sandbox'|'simulation'>('simulation');
  const [followup,setFollowup] = useState('');
  const [busy,setBusy] = useState(false);
  const [error,setError] = useState('');
  const [fundingNotice,setFundingNotice]=useState(()=>new URLSearchParams(window.location.search).get('funding')==='success');
  const [replay,setReplay] = useState(false);
  const [replayRound,setReplayRound] = useState(0);
  const [settings,setSettings] = useState(false);
  useEffect(()=>{if(!settings)return;const previous=document.activeElement as HTMLElement|null;const focusTimer=requestAnimationFrame(()=>modalRef.current?.querySelector<HTMLInputElement>('input')?.focus());const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape'){setSettings(false);return;}if(e.key==='Tab'){const items=Array.from(modalRef.current?.querySelectorAll<HTMLElement>('button,input,[href]')||[]);const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',onKey);return()=>{cancelAnimationFrame(focusTimer);document.removeEventListener('keydown',onKey);previous?.focus();};},[settings]);
  const [token,setToken] = useState(sessionStorage.getItem('accord-admin-token') || '');
  const [historyOpen,setHistoryOpen] = useState(false);
  const [explain,setExplain] = useState(false);
  const [composer,setComposer] = useState(false);
  const observerState=useRef({replay:false,composer:false,auction:null as Auction|null});
  observerState.current={replay,composer,auction};
  const initial = useRef(true);
  const linkedAuction=useRef<{id:string|null;completedIds:Set<string>|null}>({id:new URLSearchParams(window.location.search).get('auction'),completedIds:null});
  const clearLinkedAuction=()=>{linkedAuction.current={id:null,completedIds:null};const url=new URL(window.location.href);if(url.searchParams.has('auction')){url.searchParams.delete('auction');window.history.replaceState(null,'',url);}};
  const exchangeRef = useRef<HTMLDivElement>(null);
  const focusExchange = () => requestAnimationFrame(()=>exchangeRef.current?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'}));
  const refresh = async () => {
    const d = await api<PresentationBootstrap>('/api/bootstrap');
    setData(d);
    const state=observerState.current;
    if(initial.current){setError('');setIntent(d.scenarios[0]?.prompt||'');setScenario(d.scenarios[0]?.id||'dating');setMode(d.capabilities.live_agents?'live':'simulation');initial.current=false;}
    if(!state.replay&&!state.composer){
      const recent=d.auctions.filter(a=>!a.id.startsWith('recorded:')).sort((a,b)=>Date.parse(b.created_at)-Date.parse(a.created_at));
      let incoming=recent.find(a=>active(a)) || recent.find(a=>a.status==='completed') || recent[0];
      const linked=recent.find(a=>a.id===linkedAuction.current.id);
      if(linked){
        if(active(linked)){incoming=linked;}
        else if(!linkedAuction.current.completedIds){linkedAuction.current.completedIds=new Set(recent.map(a=>a.id));incoming=linked;}
        else {const newer=recent.find(a=>!linkedAuction.current.completedIds!.has(a.id));if(newer){clearLinkedAuction();incoming=newer;}else{incoming=linked;}}
      }
      if(incoming){
        const same=state.auction?.id===incoming.id;
        const stale=same&&Date.parse(incoming.updated_at)<Date.parse(state.auction!.updated_at);
        if(!stale){setAuction(incoming);setScenario(incoming.scenario);setIntent(incoming.intent);setMode(incoming.mode);setPaymentMode(incoming.payment_mode||'simulation');}
      }
    }
    return d;
  };
  useEffect(()=>{
    let stopped=false,fetching=false;
    const sync=async()=>{if(fetching||stopped)return;fetching=true;try{await refresh();}catch(e){if(!stopped)setError((e as Error).message);}finally{fetching=false;}};
    sync(); const timer=setInterval(sync,1000);
    return()=>{stopped=true;clearInterval(timer);};
  },[]);
  const s = data?.scenarios.find(x=>x.id===scenario);
  const brands = auction?.bidders.map(b=>b.brand) || data?.brands.filter(b=>b.scenario===scenario) || [];
  const latest = auction?.rounds.at(-1);
  const round = replay ? auction?.rounds[replayRound] : latest;
  const leader = round?.offers.find(o=>o.brand_id===round.leader_id);
  const winner = replay ? (replayRound === (auction?.rounds.length || 0)-1 ? auction?.winner : undefined) : auction?.winner;
  const cashLeader = round?.offers.find(o=>o.brand_id===round.cash_leader_id);
  const selected = winner || leader;
  const chosenBrand = data?.brands.find(b=>b.id===selected?.brand_id);
  const receipt = data?.ledger.find(l=>l.auction_id===auction?.id && l.kind==='click');
  const consumerUrl=data?.presentation?.consumers[scenario];
  const transfer = data?.ledger.find(l=>l.auction_id===auction?.id && l.kind==='transfer');
  const chooseScenario = (id:ScenarioId) => { if(active(auction) && !replay) return; setScenario(id);setIntent(data?.scenarios.find(x=>x.id===id)?.prompt || '');setAuction(null);sessionStorage.removeItem('accord-current-auction');setReplay(false);setFollowup('');setError(''); };
  const run = async (nextIntent?:string) => { const requestIntent=nextIntent || intent; if(!requestIntent.trim() || !s)return;setBusy(true);setError('');setReplay(false);try {const created=await post<Auction>(`/api/demo/${scenario}/auctions`, {intent:requestIntent,preferences:s.preferences,mode,payment_mode:paymentMode,target_score:85,max_rounds:5});clearLinkedAuction();setAuction(created);setComposer(false);observerState.current={...observerState.current,composer:false,auction:created};setIntent(requestIntent);setFollowup('');sessionStorage.setItem('accord-current-auction',created.id);focusExchange();}catch(e){setError((e as Error).message);}finally{setBusy(false);} };
  const action = async (action:string) => { if(!auction)return;setBusy(true);setError('');try{setAuction(await post<Auction>(`/v1/auctions/${auction.id}/actions`,{action}));await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);} };
  const click = async () => {if(!auction?.placement || replay)return;setBusy(true);try{const result=await post<{placement:NonNullable<Auction['placement']>; destination:string}>(`/v1/placements/${auction.placement.id}/click`,{});setAuction({...auction,placement:result.placement});await refresh();window.open(result.destination,'_blank','noopener,noreferrer');}catch(e){setError((e as Error).message);}finally{setBusy(false);} };
  const loadReplay = (a:Auction) => {setAuction(a);setScenario(a.scenario);setIntent(a.intent);setReplay(true);setComposer(false);observerState.current={replay:true,composer:false,auction:a};setReplayRound(0);setHistoryOpen(false);setTab('exchange');focusExchange();};

  const controls = auction&&active(auction)&&!replay ? <div className="auction-controls">{auction.status==='paused'?<button className="button secondary" disabled={busy} onClick={()=>action('continue')}><Play size={15}/>Continue</button>:<button className="button secondary" disabled={busy||auction.pause_requested} onClick={()=>action('pause')}><Pause size={15}/>{auction.pause_requested?'Pausing…':'Pause'}</button>}<button className="button primary" disabled={busy||!latest?.offers.length} onClick={()=>action('accept')}><Check size={16}/>Accept best offer</button><button className="icon-btn" disabled={busy} onClick={()=>action('cancel')} aria-label="Cancel auction" title="Cancel auction"><X size={18}/></button></div> : null;
  const roundState = replay?'Recorded replay':auction?.status==='assessing'?'Assessing personal fit':auction?.status==='paused'?'Paused':auction?.status==='running'?auction.round_started_at?'Negotiating privately':'Preparing next round':auction?.status==='completed'?'Negotiation complete':auction?.status==='cancelled'?'Cancelled':auction?.status==='failed'?'Needs attention':'Ready for a request';
  const modeLabel = replay?'Read-only replay':`${mode==='live'?'Live GPT agents':'Rule-based simulation'} · ${(auction?.payment_mode||paymentMode)==='sandbox'?'Stripe sandbox':'simulated funds'}`;

  return <MotionConfig reducedMotion="user"><div className={`shell ${auction&&!composer&&tab==='exchange'?'has-auction':''}`}>
    <a className="skip-link" href="#main">Skip to exchange</a>
    <header className="site-header"><div className="nav-inner"><button className="brand" onClick={()=>setTab('exchange')} aria-label="Accord exchange"><AccordMark/><span>accord</span></button><nav aria-label="Main navigation"><button aria-current={tab==='exchange'?'page':undefined} onClick={()=>setTab('exchange')}>Exchange</button><button aria-current={tab==='studio'?'page':undefined} onClick={()=>setTab('studio')}>Campaigns</button><button aria-current={tab==='ledger'?'page':undefined} onClick={()=>setTab('ledger')}>Ledger</button></nav><div className="nav-end"><span className="prototype-badge">Test mode · {data?.capabilities.stripe?'Stripe sandbox':'Simulated funds'}</span><button className="icon-btn" onClick={()=>setSettings(true)} title="Connection settings" aria-label="Connection settings"><Settings2 size={19}/></button><button className="text-button" onClick={async()=>{try{const response=await fetch('/api/session',{method:'DELETE'});if(!response.ok)throw new Error('Could not sign out. Please retry.');sessionStorage.removeItem('accord-admin-token');window.location.reload();}catch(e){setError((e as Error).message);}}}>Sign out</button></div></div></header>
    <main id="main">
      <section className="page-heading"><div className="heading-copy"><span className="eyebrow">Accord / control plane</span><h1>{tab==='exchange'?'Exchange operations':tab==='studio'?'Campaign management':'Settlement ledger'}</h1></div><div className="header-stats">{tab==='exchange'&&<><span><small>Agents</small><b>{brands.length}</b></span><span><small>Round</small><b>{auction?`${replay?round?.number||0:auction.current_round} / ${auction.max_rounds}`:'— / 5'}</b></span><span className="request-id"><small>Request</small><b title={auction?.id}>{auction?auction.id.slice(0,12):'Awaiting request'}</b></span></>}<button className="button secondary history-button" onClick={()=>setHistoryOpen(!historyOpen)}><RotateCcw size={14}/>History<ChevronDown size={13}/></button></div></section>
      {historyOpen&&<section className="history-panel"><div className="panel-heading"><h2>Past negotiations</h2><span>Read-only. No billing.</span><button className="icon-btn" onClick={()=>setHistoryOpen(false)} aria-label="Close auction history"><X size={18}/></button></div>{data?.auctions.filter(a=>!active(a)).length?data.auctions.filter(a=>!active(a)).map(a=><button className="history-item" key={a.id} onClick={()=>loadReplay(a)}><span className="history-icon">{iconFor(a.scenario)}</span><div><b>{data.scenarios.find(sc=>sc.id===a.scenario)?.app_name}</b><p>{a.intent}</p></div><small>{a.id.startsWith('recorded:')?'Recorded live GPT · Sep 28':`${a.rounds.length} rounds · ${a.mode}`}</small><Play size={15}/></button>):<p className="empty-copy">Completed auctions will appear here.</p>}</section>}
      {fundingNotice&&<div className="notice" role="status"><Check size={18}/><div><b>Checkout completed.</b> Funds appear after Stripe confirms payment.</div><button className="icon-btn" aria-label="Dismiss checkout confirmation" onClick={()=>{setFundingNotice(false);const url=new URL(window.location.href);url.searchParams.delete('funding');window.history.replaceState(null,'',url);}}><X size={17}/></button></div>}
      {error&&<div className="notice error" role="alert"><span>{error}</span><button className="icon-btn" aria-label="Dismiss error" onClick={()=>setError('')}><X size={17}/></button></div>}
      {!data?<div className="loading-panel"><span className="spinner"/><h2>Connecting your workspace</h2><p>The exchange will appear here in a moment.</p><button className="button secondary" onClick={()=>refresh().catch(e=>setError(e.message))}>Retry connection</button></div>:<>
      {tab==='exchange'&&<>
        <div className="consumer-toolbar"><span>Example integrations</span><div className="consumer-links">{data.scenarios.map(sc=>{const url=data.presentation?.consumers[sc.id];return url?<a key={sc.id} href={url} target="_blank" rel="noreferrer">{iconFor(sc.id)}{sc.app_name}<ArrowUpRight size={14}/></a>:<span key={sc.id}>{iconFor(sc.id)}{sc.app_name}</span>;})}</div><button className="text-button" disabled={active(auction)&&!replay} onClick={()=>{setComposer(!composer);observerState.current.composer=!composer;}}>{composer?<X size={15}/>:<Plus size={15}/>} {composer?'Close test':'Test a request'}</button>{!auction&&<button className="text-button" onClick={()=>setHistoryOpen(!historyOpen)}><RotateCcw size={15}/>Replay</button>}</div>
        <div className="exchange-meta"><span className="mode-chip"><span className={`status-dot ${active(auction)&&!replay?'live':''}`}/>{modeLabel}</span><span className="watch-note">{replay?'Original decisions, preserved.':'Listening for requests from connected apps.'}</span>{replay&&<button className="text-button" onClick={()=>{clearLinkedAuction();setReplay(false);observerState.current.replay=false;refresh().catch(e=>setError(e.message));}}>Return to live<ArrowRight size={14}/></button>}</div>
        {composer&&<div className="test-toolbar"><div className="scenario-switch">{data.scenarios.map(sc=><button key={sc.id} aria-pressed={scenario===sc.id} disabled={active(auction)&&!replay} onClick={()=>chooseScenario(sc.id)}>{iconFor(sc.id)}{sc.name}</button>)}</div><label>Agents<select value={mode} disabled={active(auction)&&!replay} onChange={e=>{setMode(e.target.value as typeof mode);if(e.target.value==='simulation')setPaymentMode('simulation');}}><option value="simulation">Simulation</option><option value="live" disabled={!data.capabilities.live_agents}>Live GPT</option></select></label><label>Funds<select value={paymentMode} disabled={active(auction)&&!replay||mode==='simulation'} onChange={e=>setPaymentMode(e.target.value as typeof paymentMode)}><option value="simulation">Simulated</option><option value="sandbox" disabled={!data.capabilities.stripe}>Stripe sandbox</option></select></label></div>}
        <div className="exchange-grid" ref={exchangeRef}>
          {composer?<section className="request-panel test-request"><span className="eyebrow">Test request</span><div className="origin-app">{iconFor(scenario)}<h2>{s?.app_name}</h2></div><label htmlFor="intent">What are you looking for?</label><textarea id="intent" rows={5} value={intent} onChange={e=>setIntent(e.target.value)} disabled={active(auction)&&!replay}/><div className="preference-list">{s?.preferences.map(p=><span key={p}>{p}</span>)}</div><button className="button primary" disabled={busy||active(auction)&&!replay||mode==='live'&&!data.capabilities.live_agents||!intent.trim()} onClick={()=>run()}>{busy?<span className="spinner small"/>:<Sparkles size={16}/>}Start negotiation<ArrowRight size={16}/></button><p className="small-note">This utility sends the same request a connected consumer app would send.</p></section>:<motion.aside key={auction?.id||'waiting'} className="request-panel" initial={{opacity:0,y:reduceMotion?0:10}} animate={{opacity:1,y:0}} transition={{duration:reduceMotion?0:.3}}><span className="eyebrow">{auction?'Incoming request':'Request gateway'}</span><div className="origin-app">{iconFor(scenario)}<h2>{auction?s?.app_name:'Waiting for a request'}</h2></div><p className="request-intent">{auction?auction.intent:'Open a consumer app, start a conversation, and ask for a recommendation. Its agent will bring the request here.'}</p>{auction&&<><div className="preference-list">{auction.preferences.map(p=><span key={p}>{p}</span>)}</div><details className="request-details"><summary>Request details<ChevronDown size={14}/></summary><dl><div><dt>Publisher</dt><dd>{auction.publisher_id}</dd></div><div><dt>Received</dt><dd>{new Date(auction.created_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</dd></div><div><dt>Request ID</dt><dd>{auction.id}</dd></div></dl></details></>}{consumerUrl&&<a className="text-button origin-link" href={consumerUrl} target="_blank" rel="noreferrer">Open {s?.app_name}<ArrowUpRight size={15}/></a>}{winner&&<div className="returned-offer"><span><Check size={15}/>Offer returned to the app</span><h3>{winner.brand_name}</h3><strong>{money(winner.effective_price_cents)}</strong><p>{money(winner.discount_cents)} off the original price.</p><code>{chosenBrand?.code}</code><small>Illustrative code. No redemption.</small></div>}</motion.aside>}
          <section className="exchange-main"><div className="board-heading"><div><span className="eyebrow">{replay?'Replay':'Auction control'}</span><h2>{winner?`Selected · ${winner.brand_name} · ${money(winner.effective_price_cents)}`:auction?'Live negotiation':'Awaiting publisher request'}</h2></div>{controls}</div>
            <div className={`auction-progress ${active(auction)&&!replay?'running':''}`}><div className="progress-label"><span className={`status-dot ${auction?.status==='running'&&!replay?'live':''}`}/><b>{roundState}</b><span>{auction?`Round ${replay?round?.number||0:auction.current_round} of ${auction.max_rounds}`:'Up to 5 rounds'}</span></div><div className="progress-steps" role="progressbar" aria-label="Completed rounds" aria-valuemin={0} aria-valuemax={auction?.max_rounds||5} aria-valuenow={round?.number||0}>{Array.from({length:auction?.max_rounds||5},(_,i)=><span key={i} className={`${i<(round?.number||0)?'done':''} ${!replay&&auction?.status==='running'&&i===auction.current_round-1?'current':''}`}/>)}</div><button className="text-button" onClick={()=>setExplain(!explain)}>Scoring<CircleHelp size={13}/></button></div>
            {auction?.status==='running'&&!!auction.round_started_at&&!replay&&<p className="sealed-note"><ShieldCheck size={14}/>10-second sealed round. Offers publish together when the window closes; the board shows the last completed round.</p>}

            {explain&&<div className="explanation"><div><h3>User value comes first.</h3><p>Personal fit contributes 60% of the score; effective price contributes 40%. A higher advertising bid only breaks an exact tie. Fit is assessed before bidding and stays fixed for this request.</p></div><button className="icon-btn" aria-label="Close scoring explanation" onClick={()=>setExplain(false)}><X size={17}/></button></div>}
            {round&&round.number>1&&auction?.rounds[round.number-2]?.leader_id!==round.leader_id&&round.leader_id&&<div className="lead-change-note" role="status"><ArrowRight size={16}/><p><b>{leader?.brand_name} takes the lead</b> with an effective price of {money(leader?.effective_price_cents)}.</p></div>}
            <LiveOperations auction={auction} replay={replay}/><div className="offers-heading"><h3>Public offer board</h3><span>{round?`Committed round ${round.number}`:'No submissions committed'}</span></div><LayoutGroup id={auction?.id||'waiting'}><div className="brand-grid">{brands.map((brand,i)=>{const bidder=auction?.bidders.find(b=>b.brand.id===brand.id);const offer=round?.offers.find(o=>o.brand_id===brand.id);const previousOffer=round&&round.number>1?auction?.rounds[round.number-2]?.offers.find(o=>o.brand_id===brand.id):undefined;const actionValue=round?.actions[brand.id]||auction?.rounds.slice(0,round?.number||0).reverse().map(r=>r.actions[brand.id]).find(Boolean);const explanation=typeof actionValue==='object'?actionValue.explanation:typeof actionValue==='string'?actionValue:bidder?.fit.explanation;return <BrandCard key={`${auction?.id||'waiting'}-${brand.id}`} brand={brand} index={i} offer={offer} previousOffer={previousOffer} offerRound={round?.number} sealed={auction?.status==='running'&&!!auction.round_started_at&&!replay&&!bidder?.finalized&&!bidder?.withdrawn} fit={auction?.status==='assessing'?undefined:bidder?.fit.score} fitExplanation={auction?.status==='assessing'?undefined:bidder?.fit.explanation} leader={round?.leader_id===brand.id} winner={winner?.brand_id===brand.id} running={!!auction&&['running','assessing'].includes(auction.status)&&!replay} explanation={explanation} action={offer?.finalized?'finalized':typeof actionValue==='object'?actionValue.action:actionValue} withdrawn={replay?typeof actionValue==='object'&&actionValue.action==='withdraw':bidder?.withdrawn}/>;})}</div></LayoutGroup>
            {selected&&cashLeader&&<section className={`comparison ${selected.brand_id!==cashLeader.brand_id?'value-won':''}`}><div className="comparison-title"><h3>{selected.brand_id!==cashLeader.brand_id?'User-value winner ≠ highest cash bidder':'Selection result'}</h3><p>{selected.brand_id!==cashLeader.brand_id?`${selected.brand_name} ${winner?'won':'leads'} on user value with a lower CPC.`:'The advertising bid pays the app. The discount benefits the customer.'}</p></div><div className="comparison-numbers"><div><span>Highest cash bid</span><strong>{money(cashLeader.bid_cents)}</strong><small>{cashLeader.brand_name}</small></div><div><span>{winner?'Winning':'Leading'} bid</span><strong>{money(selected.bid_cents)}</strong><small>{selected.brand_name}</small></div><div><span>Customer pays</span><strong>{money(selected.effective_price_cents)}</strong><small>{money(selected.discount_cents)} saved</small></div></div></section>}
            <section className="timeline"><div className="panel-heading"><h3>Negotiation history</h3><span>{replay?'Select a round to inspect its offers.':'The public record of each completed round.'}</span></div><div className="round-track">{Array.from({length:auction?.max_rounds||5},(_,i)=>{const r=auction?.rounds[i];const changed=i>0&&r?.leader_id&&r.leader_id!==auction?.rounds[i-1]?.leader_id;return <button key={i} disabled={!replay||!r} className={`round-node ${r?'complete':''} ${round?.number===i+1?'current':''}`} onClick={()=>setReplayRound(i)}><span>{r?<Check size={15}/>:i+1}</span><b>Round {i+1}</b><small>{r?changed?'Leader changed':r.offers.find(o=>o.brand_id===r.leader_id)?.brand_name||'No offer':auction?.current_round===i+1&&active(auction)?auction.status==='paused'?'Paused':auction.round_started_at?'Negotiating':'Preparing':'Not started'}</small></button>;})}</div>{round?.feedback&&<details className="round-feedback"><summary>User agent’s feedback<ChevronDown size={15}/></summary><p>{round.feedback}</p></details>}{auction?.end_reason&&<p className="end-reason"><Check size={14}/>Finished after {auction.rounds.length} {auction.rounds.length===1?'round':'rounds'} · {statusText(auction.end_reason)}</p>}{auction?.error&&<p className="inline-error">{auction.error}</p>}</section>
            {auction?.placement&&!replay&&<PaymentReceipt auction={auction} receipt={receipt} transfer={transfer} transfers={data.ledger.filter(l=>l.auction_id===auction.id&&l.kind==='transfer')}/>}
          </section>
        </div>
      </>}
      {tab==='studio'&&<section className="studio"><ExternalBrands request={api} onChanged={refresh}/><div className="studio-intro"><p>Managed templates and invited external agents. Catalog facts with configurable test campaigns.</p><span>Changes apply to new auctions.</span></div><div className="studio-grid">{data.brands.map(b=><CampaignCard key={b.id} brand={b} campaign={data.campaigns.find(c=>c.brand_id===b.id)!} stripe={data.capabilities.stripe} onRefresh={refresh} onError={setError}/>)}</div></section>}
      {tab==='ledger'&&<Ledger ledger={data.ledger} brands={data.brands} stripe={data.capabilities.stripe}/>}
      <footer><span className="footer-brand"><AccordMark/>accord</span><p>Test campaigns use real brand references and fictional offers. No merchant affiliation or coupon redemption.</p><span>Built for agent commerce.</span></footer>
      </>}
    </main>
    {settings&&<div className="modal-overlay" onClick={()=>setSettings(false)}><section ref={modalRef} role="dialog" aria-modal="true" aria-labelledby="connection-title" className="modal" onClick={e=>e.stopPropagation()}><button className="icon-btn modal-close" aria-label="Close connection settings" onClick={()=>setSettings(false)}><X size={20}/></button><span className="eyebrow">Workspace connection</span><h2 id="connection-title">Connect your controls.</h2><p>If your server requires an admin token, enter it here. It stays in this browser session and is sent only to this application.</p><label>Admin token<input type="password" value={token} onChange={e=>setToken(e.target.value)} autoComplete="off"/></label><button className="button primary" onClick={()=>{sessionStorage.setItem('accord-admin-token',token);setSettings(false);setError('');refresh().catch(e=>setError(e.message));}}>Save connection<ArrowRight size={17}/></button></section></div>}
  </div></MotionConfig>;
}

function AccordMark(){return <svg viewBox="0 0 32 36" aria-hidden="true" fill="none"><path d="m16 2 13 7.5v7L16 9 3 16.5v-7L16 2Z" fill="currentColor"/><path d="m3 19 6-3.5V24l7 4 7-4v-8.5l6 3.5v8L16 34 3 27v-8Z" fill="currentColor"/><path d="m16 12 6 3.5v7L16 26l-6-3.5v-7l6-3.5Z" fill="#eea85a"/></svg>}

function BrandCard({brand,index,offer,previousOffer,offerRound,sealed,fit,fitExplanation,leader,winner,running,explanation,action,withdrawn}:{brand:Brand;index:number;offer?:RankedOffer;previousOffer?:RankedOffer;offerRound?:number;sealed:boolean;fit?:number;fitExplanation?:string;leader:boolean;winner:boolean;running:boolean;explanation?:string;action?:string;withdrawn?:boolean}) {
  const reduced=useReducedMotion();
  const discountChange=offer&&previousOffer?offer.discount_cents-previousOffer.discount_cents:0;
  const state=withdrawn?'Withdrawn':winner?'Selected offer':sealed?'Negotiating':offer?.finalized?'Final offer':leader?'Leading offer':offer?'Offer received':running?'Assessing fit':'Ready';
  return <motion.article initial={{opacity:0,y:reduced?0:12}} animate={{opacity:withdrawn?.55:1,y:0}} transition={{duration:reduced?0:.3,delay:reduced?0:index*.06}} className={`brand-card ${leader?'leader':''} ${winner?'winner':''}`}>
    {leader&&<motion.div layoutId="current-leader" className="leader-marker" transition={{duration:reduced?0:.25}}/>}
    <div className="brand-card-top"><div className="brand-monogram" style={{background:brand.color}}>{brand.initials}</div><span className={`brand-state ${leader?'highlight':''}`}>{winner?<Check size={13}/>:sealed?<span className="sealed-dots" aria-hidden="true"><i/><i/><i/></span>:null}{state}</span></div>
    <div className="brand-identity"><h3>{brand.name}</h3><p>{brand.item}</p></div>
    <div className="brand-price"><span>{sealed&&offer?`Last public price · round ${offerRound}`:'Customer price'}</span><div><strong><AnimatedValue value={offer?money(offer.effective_price_cents):money(brand.base_price_cents)}/></strong>{!!offer?.discount_cents&&<s>{money(brand.base_price_cents)}</s>}</div><small>{brand.price_kind==='demo_quote'?'Test quote':'Catalog price snapshot'}</small></div>
    <div className="offer-pair"><div><span>Advertising bid</span><b><AnimatedValue value={offer?money(offer.bid_cents):'—'}/></b><small>per click</small></div><div><span>Customer discount</span><b className="discount"><AnimatedValue value={offer?money(offer.discount_cents):'—'}/></b><small>off the price</small></div></div>
    <div className="discount-change-slot">{discountChange>0?<motion.span key={`${offerRound}-${offer?.discount_cents}`} initial={{opacity:0,y:reduced?0:5}} animate={{opacity:1,y:0}}><Plus size={13}/>{money(discountChange)} more for you this round</motion.span>:<span>{offer?.finalized?'This agent has made its final offer.':sealed?'The next offer stays private until the round closes.':offer?'Available on the public offer board.':'Waiting for the first offer.'}</span>}</div>
    <div className="value-score"><span>User value</span><b><AnimatedValue value={offer?offer.user_score.toFixed(1):'—'}/><small>/100</small></b></div>
    <details className="agent-details"><summary>Why this offer?<ChevronDown size={15}/></summary><div className="detail-scores"><div><span>Personal fit</span><b>{fit===undefined?'—':`${fit}/100`}</b></div><div><span>Price score</span><b>{offer?`${offer.price_score.toFixed(1)}/100`:'—'}</b></div></div>{fitExplanation&&<p>{fitExplanation}</p>}<h4>The brand agent’s decision</h4><p>{explanation||brand.description}</p><small>Personal fit is fixed before bidding. {action?`Latest action: ${statusText(action)}.`:''}</small><a className="source-link" href={brand.source_url} target="_blank" rel="noreferrer">View catalog source<ArrowUpRight size={13}/></a></details>
  </motion.article>;
}

function CampaignCard({brand,campaign,stripe,onRefresh,onError}:{brand:Brand;campaign:Campaign;stripe:boolean;onRefresh:()=>Promise<unknown>;onError:(s:string)=>void}) {
  const [editing,setEditing] = useState(false);
  const [bid,setBid] = useState(String((campaign?.max_cpc_cents||0)/100));
  const [discount,setDiscount] = useState(String((campaign?.max_discount_cents||0)/100));
  const [strategy,setStrategy] = useState(campaign?.strategy||'');
  const [busy,setBusy] = useState(false);
  const save = async () => {setBusy(true);try{await api(`/v1/campaigns/${brand.id}`,{method:'PATCH',body:JSON.stringify({max_cpc_cents:Math.round(Number(bid)*100),max_discount_cents:Math.round(Number(discount)*100),strategy,active:campaign.active})});await onRefresh();setEditing(false);}catch(e){onError((e as Error).message);}finally{setBusy(false);}};
  const fund = async (simulation:boolean) => {setBusy(true);try{const r=await post<{url?:string}>(simulation?`/api/simulation/fund/${brand.id}`:`/v1/campaigns/${brand.id}/fund`,{amount_cents:10000});if(r.url)window.location.assign(r.url);else await onRefresh();}catch(e){onError((e as Error).message);}finally{setBusy(false);}};
  const toggle = async () => {setBusy(true);try{await api(`/v1/campaigns/${brand.id}`,{method:'PATCH',body:JSON.stringify({active:!campaign.active})});await onRefresh();}catch(e){onError((e as Error).message);}finally{setBusy(false);}};
  if(!campaign)return null;
  return <article className="campaign-card"><div className="brand-identity"><div className="brand-monogram" style={{background:brand.color}}>{brand.initials}</div><div><h3>{brand.name}</h3><span>{brand.scenario} · v{campaign.version}</span></div><button className={`toggle ${campaign.active?'on':''}`} aria-label={`${campaign.active?'Pause':'Activate'} ${brand.name}`} title={campaign.active?'Active':'Paused'} disabled={busy} onClick={toggle}><span/></button></div><h4>{brand.item}</h4><p>{brand.description}</p><ul className="fact-list">{brand.facts.slice(0,3).map(f=><li key={f}><Check size={12}/>{f}</li>)}</ul><a className="source-link" href={brand.source_url} target="_blank" rel="noreferrer">Catalog source · {brand.source_date}<ArrowUpRight size={12}/></a><div className="catalog-note">{brand.price_kind==='demo_quote'?'Test quote':'Catalog snapshot'}: {money(brand.base_price_cents)} · Test campaign & illustrative code</div>{editing?<div className="campaign-form"><div className="form-row"><label>Max CPC ($)<input type="number" min="0.01" step="0.01" value={bid} onChange={e=>setBid(e.target.value)}/></label><label>Max discount ($)<input type="number" min="0" step="0.01" value={discount} onChange={e=>setDiscount(e.target.value)}/></label></div><label>Agent strategy<textarea value={strategy} onChange={e=>setStrategy(e.target.value)} rows={3}/></label><div className="form-row"><button className="button primary" onClick={save} disabled={busy}>Save strategy<Check size={14}/></button><button className="button secondary" onClick={()=>setEditing(false)}>Cancel</button></div></div>:<><div className="campaign-stats"><div><span>Max CPC</span><b>{money(campaign.max_cpc_cents)}</b></div><div><span>Max discount</span><b>{money(campaign.max_discount_cents)}</b></div><div><span>{stripe?'Sandbox available':'Simulated available'}</span><b>{money(campaign.balance_cents-campaign.reserved_cents)}</b></div></div><p className="strategy-preview">{campaign.strategy}</p><button className="button secondary full-width" onClick={()=>setEditing(true)}><Settings2 size={14}/> Edit campaign</button></>}<div className="fund-actions"><button disabled={busy||!stripe} onClick={()=>fund(false)} title={!stripe?'Stripe sandbox is not configured':undefined}><Plus size={13}/> $100 sandbox</button><button disabled={busy} onClick={()=>fund(true)}><Plus size={13}/> $100 simulated</button></div><small className="fund-note">Simulated credits are separate from Stripe funds.</small></article>;
}

function Ledger({ledger,brands,stripe}:{ledger:LedgerEntry[];brands:Brand[];stripe:boolean}) {
 const clicks=ledger.filter(l=>l.kind==='click');
 const sum=(key:'amount_cents'|'publisher_cents'|'network_cents',mode:'sandbox'|'simulation')=>clicks.filter(l=>l.mode===mode).reduce((a,l)=>a+(l[key]||0),0);
 const [filter,setFilter]=useState<'all'|'sandbox'|'simulation'>('all');
 return <section className="ledger"><div className="studio-intro"><div><h2>Funds and settlement</h2><p>Selection reserves a CPC. A click charges it. The publisher earns 80%; the network earns 20%.</p></div><span className="outline-pill">{stripe?'Stripe sandbox connected':'Stripe not configured'}</span></div><div className="ledger-stats">{(['amount_cents','publisher_cents','network_cents'] as const).map((key,i)=><div key={key}><span>{['Advertising spend','Publisher earnings','Network gross'][i]}</span><strong>{money(sum(key,'sandbox'))}</strong><small>Stripe sandbox</small><div className="simulation-total">{money(sum(key,'simulation'))}<small>simulated</small></div></div>)}</div><div className="ledger-table"><div className="ledger-table-heading"><h3>Transaction journal</h3><div className="scenario-switch">{(['all','sandbox','simulation'] as const).map(v=><button key={v} className={filter===v?'selected':''} onClick={()=>setFilter(v)}>{statusText(v)}</button>)}</div></div><div className="table-scroll"><table><thead><tr><th>Event</th><th>Brand / publisher</th><th>Amount</th><th>Mode</th><th>Status</th><th>Time</th></tr></thead><tbody>{ledger.filter(l=>filter==='all'||l.mode===filter).map(l=><tr key={l.id}><td><b>{statusText(l.kind)}</b><small>{l.id.slice(0,18)}</small></td><td>{brands.find(b=>b.id===l.brand_id)?.name||l.brand_id}<small>{l.publisher_id||'Campaign balance'}</small></td><td><b>{money(l.amount_cents)}</b></td><td><span className="tiny-pill">{l.mode}</span></td><td><span className={`ledger-status ${l.status}`}>{l.status}</span>{l.error&&<small className="inline-error">{l.error}</small>}{l.stripe_id&&<small>{l.stripe_id}</small>}</td><td>{new Date(l.created_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'})}</td></tr>)}</tbody></table>{!ledger.filter(l=>filter==='all'||l.mode===filter).length&&<div className="empty-journal"><ArrowUpRight size={28}/><h3>A clear ledger starts here.</h3><p>Fund a campaign or click a winning recommendation to see the transaction trail.</p></div>}</div></div><p className="ledger-disclaimer">Sandbox transfers are not bank payouts. Processing fees are recorded separately. Test discounts do not create cash liabilities.</p></section>;
}
